definitions:
  errcode.Error:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      msg:
        type: string
    type: object
  model.User:
    properties:
      created_by:
        type: string
      created_on:
        type: integer
      deleted_on:
        type: integer
      email:
        type: string
      id:
        type: integer
      is_del:
        type: integer
      modified_by:
        type: string
      modified_on:
        type: integer
      password:
        type: string
      state:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
  license: {}
  title: 會員系統
  version: "0.6"
paths:
  /api/v1/users:
    post:
      parameters:
      - description: 使用者帳號
        in: query
        maxLength: 100
        minLength: 3
        name: username
        required: true
        type: string
      - description: 使用者密碼
        in: query
        maxLength: 100
        minLength: 6
        name: password
        required: true
        type: string
      - description: 使用者Email
        format: email
        in: query
        name: email
        required: true
        type: string
      - default: 1
        description: 使用者狀態
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 建立者
        in: query
        maxLength: 100
        minLength: 3
        name: created_by
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: 請求錯誤
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 內部錯誤
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 創建帳號
swagger: "2.0"
